### ISSUE TITLE
elabctl backup doesn't honor non-standard locations for uploaded files

### ISSUE THREAD

**Issue by mjeltsch** [elabftw/elabctl#11]
Our university's server farm offers variable and expandable server space via a separate /data block device. Hence I need to put the uploaded files somewhere under that directory. The corresponding section of our elabftw.yml file looks like this:
```
    volumes:
        # this is where you will keep the uploaded files persistently
        # host:container
        - /data/elabftw/web:/elabftw/uploads
```
However, it seems that the "elabctl backup" command doesn't backup the files in my directory at all, and also doesn't generate an error message, because the /var/elabftw/web directory exists in my case, but is unused, since the files are uploaded to /data/elabftw/web. In order to use the elabftw backup, it should use the volumes defined in /etc/elabftw.yml or accept a command line argument to change the default behavior.

**Comment by NicolasCARPi** [comment]
Hello,

Yes, there is no support for non standard location at the moment. What you can do is edit the file `/usr/bin/elabctl` and change the values of DATA_DIR and BACKUP_DIR. Then it should work. Keep in mind that your change will be overwritten if you run `elabctl self-update`.

I will probably add a way to configure that properly, maybe with a /etc/elabctl.conf that would override default values.

**Comment by NicolasCARPi** [comment]
Hello,

There is now support for custom installation paths. If you place a file at `/etc/elabctl.conf` it will be read and override the defaults. You can see an example here: https://raw.githubusercontent.com/elabftw/elabctl/master/elabctl.conf.

When you install for first time it shows the default paths and ask if it's fine before installing anything.

Thanks for your contribution :)

Cheers,
~Nico
