### ISSUE TITLE
Backup only runs when elabctl is started

### ISSUE THREAD

**Issue by cbuhl** [elabftw/elabctl#17]
I use elabctl v0.6.3.

This will most likely require a bit more information, which I'll be happy to provide when asked.

I wanted to update my elabftw to the most recent version, and I ssh'ed into the server, ran 
`sudo elabctl stop`
`sudo elabctl update`

It returned the following, and immediately returned to the prompt, seemingly without doing anything;
```
__@elabftw01:~$ sudo elabctl update
elabctl © 2017 Nicolas CARPi - https://www.elabftw.net
Version: 0.6.3
Using configuration file: /etc/elabftw.yml

Before updating, a backup will be created.
Using backup directory /var/backups/elabftw
__@elabftw01:~$ ls /var/backups/elabftw/
```
I checked the backup directory, and it did not create any files.
I then started the server again (`sudo elabctl start`), and reran the update. This time it did not return to the prompt immediately, but did in fact generate the backup files, and also carried out the update.

After restarting the services, I am met with only an error message;
SQLSTATE[HY000] [2002] Connection refused
Or a similar message regarding a timeout.

I restarted the server it is running on, and after restarting the service, I can monitor the status with `elabctl status`, consecutively:

```
__@elabftw01:~$ sudo elabctl status
elabctl © 2017 Nicolas CARPi - https://www.elabftw.net
Version: 0.6.3
Using configuration file: /etc/elabftw.yml

 Name               Command               State             Ports         
-------------------------------------------------------------------------
elabftw   /run.sh                       Up           0.0.0.0:443->443/tcp 
mysql     docker-entrypoint.sh mysqld   Restarting                        
__@elabftw01:~$ sudo elabctl status
elabctl © 2017 Nicolas CARPi - https://www.elabftw.net
Version: 0.6.3
Using configuration file: /etc/elabftw.yml

 Name               Command             State          Ports         
--------------------------------------------------------------------
elabftw   /run.sh                       Up      0.0.0.0:443->443/tcp 
mysql     docker-entrypoint.sh mysqld   Up      3306/tcp, 33060/tcp  
__@elabftw01:~$ sudo elabctl status
elabctl © 2017 Nicolas CARPi - https://www.elabftw.net
Version: 0.6.3
Using configuration file: /etc/elabftw.yml

 Name               Command               State             Ports         
-------------------------------------------------------------------------
elabftw   /run.sh                       Up           0.0.0.0:443->443/tcp 
mysql     docker-entrypoint.sh mysqld   Restarting                        
__@elabftw01:~$ sudo elabctl status
elabctl © 2017 Nicolas CARPi - https://www.elabftw.net
Version: 0.6.3
Using configuration file: /etc/elabftw.yml

 Name               Command             State          Ports         
--------------------------------------------------------------------
elabftw   /run.sh                       Up      0.0.0.0:443->443/tcp 
mysql     docker-entrypoint.sh mysqld   Up      3306/tcp, 33060/tcp  
__@elabftw01:~$ sudo elabctl status
elabctl © 2017 Nicolas CARPi - https://www.elabftw.net
Version: 0.6.3
Using configuration file: /etc/elabftw.yml

 Name               Command               State             Ports         
-------------------------------------------------------------------------
elabftw   /run.sh                       Up           0.0.0.0:443->443/tcp 
mysql     docker-entrypoint.sh mysqld   Restarting                        
__@elabftw01:~$ sudo elabctl status
elabctl © 2017 Nicolas CARPi - https://www.elabftw.net
Version: 0.6.3
Using configuration file: /etc/elabftw.yml

 Name               Command               State             Ports         
-------------------------------------------------------------------------
elabftw   /run.sh                       Up           0.0.0.0:443->443/tcp 
mysql     docker-entrypoint.sh mysqld   Restarting   
```

Note the mysql; In the beginning it toggles between Up and Restarting, but then it settles on Restarting. 

This is a bit beyond my skill-set - what should I try next?

**Comment by NicolasCARPi** [comment]
> I use elabctl v0.6.3.

You mean 1.6.3 right?

Yes, the backup command needs the containers to be running (`elabctl self-update` to update elabctl).

Make sure to read the realease note for 2.0.0: https://doc.elabftw.net/how-to-update.html#breaking-update.

As for the container, you can check the logs of a container with:

~~~bash
docker logs mysql
~~~

You'll probably see an error related to the container restarting.

**Comment by NicolasCARPi** [comment]
and `sudo elabctl self-update` to update to latest version (you can then use it without sudo if your user is in the docker group).

**Comment by cbuhl** [comment]
I actually had 0.6.3, initially. After the elabctl self-update, I have v1.0.1, and I am seemingly unable to update further. 

I found the error in an analogue fashion - unused docker images were filling up my server, and that culled the mysql at startup. I don't know if it's possible to add a check/warning for e.g. 1GB available space when updating elabFTW?

**Comment by NicolasCARPi** [comment]
We mixed the version of elabctl and the version of elabftw! I was talking about the elabftw version! Latest elabctl version is 1.0.1 yes.

> I don't know if it's possible to add a check/warning for e.g. 1GB available space when updating elabFTW?

This is done already, it's just not published yet:
https://github.com/elabftw/elabctl/blob/next/elabctl.sh#L116-L134
