### ISSUE TITLE
Self-signed certificate request ignored by installer script?

### ISSUE THREAD

**Issue by mjeltsch** [elabftw/elabctl#20]
Hi,
I am just moving our elabftw install from ubuntu 18.04 to 20.04. Before doing that, I test-installed (for curiosity) a fresh version of elabftw on the newly created virtual server and always ran into trouble since elabctl status always showed the elabftw container as "Up (unhealthy)". I repeated the process a few times since I do not trust myself. But finally, I inspected the generated /etc/elabftw.yml file and realized that ENABLE_LETSENCRYPT=true. I had not set up Letsencrypt since I wanted to use self-signed certificates and had chosen that option during the installation. After manually setting ENABLE_LETSENCRYPT=false, everything worked perfectly. So obviously choosing to use self-signed certificates is not honored by the installer script. I repeated the install (deleting the existing /etc/elabftw.yml file) and again, my request was not honored. Even though I fully agree with you to get a "real" certificate, there are plenty of use cases where self-signed certs are needed, e.g. test installations. And since our elabftw install is only available inside our university's firewall, I need to get the certs from our university (and install them manually), which is usually the last thing to do after everything else works...

**Comment by NicolasCARPi** [comment]
As you can see from the code (https://github.com/elabftw/elabctl/blob/master/elabctl.sh#L326-L330) `ENABLE_LETSENCRYPT` is set to `true` if you have a (sub)domain (now a requirement in fact, I'll need to change that question). So did you answer yes at the second question?

To be clear, there are four options:

1. Run the container in HTTP mode (requires a reverse proxy) -> no certs involved
2. Have an externally reachable domain and use LE certificates
3. Use your own certificates (self-signed or not)
4. Let the container generate certificates

You should have reached this line: https://github.com/elabftw/elabctl/blob/master/elabctl.sh#L285 if you want it to generate certs.

I believe you want to use option 3, right? For that you need to have `ENABLE_LETSENCRYPT=true`, the name is confusing I know, but see that comment in the code:
`# even if we don't use Let's Encrypt, for using TLS certs we need this to be true, and volume mounted`

I know I need to change this to better and clearer var names.

So in the end it makes sense to have ENABLE_LE to true to place your own certs, and to false to let it generate certs. Is it more clear for you now?

**Comment by mjeltsch** [comment]
Hi,
I think I do understand all the different options since I used so far all
of them except option 1. I just wanted to try out elabftw, so actually I
wanted option 4 (least amount of work), but that seems not to be reachable
by running the installer script without later manually modifying the
/etc/elabftw.yml file, correct? By carefully reading all the documentation
I would not have stumbled over this. But you are correct in that the
wording could be more self-explainable.

Cheers,
Michael

**Comment by NicolasCARPi** [comment]
You're correct, there was a bug, it has been corrected, please feel free to get the latest version and try it out!
