### ISSUE TITLE
elabctl entries for docker-compose lacking required "-"

### ISSUE THREAD

**Issue by rtis** [elabftw/elabctl#22]
When doing a fresh install of current image (From web page: ,Installed version: 4.2.0-BETA Latest version: 4.1.0),
"elabctl start" fails at line that should invoke docker-compose.  Since the "-" is missing in the elabctl script, that cmd 
is interpreted as a docker command and fails with a cmd line syntax error.  Editing the downloaded elabctl script to
insert the proper "-" in 4 places corrects the problem and elabftw installs properly.

Not sufficiently familiar with git to send off a proper patch, but the fix is pretty obvious and only shows up in four
lines.  Verified that latest elabctl github version shows the above error.

Otherwise, latest version seems to be working properly.......great app.

Regards,
rtisys

**Comment by alexander-haller** [comment]
On Debian stable 11.1 elabctl 2.3.*  also breaks elabctl with the docker version "20.10.5+dfsg1, build 55c4c88".
`docker compose` does not exist there.

Can I replace  `if [ "$docker_version" -lt 20 ]; then` to "    `if [ "$docker_version" -lt 21 ]; then`  in 
elabctl.sh#L444
And `declare DC="docker-compose"` 

Currently thinking if it is better to replace this over including the external docker repos and upgrading away from the Debian repo.

**Comment by NicolasCARPi** [comment]
Yeah sure, elabctl is just a wrapper to docker-compose anyway. I'll look more into it for the versions, I might not have gotten it right.

**Comment by raymundfueloep** [comment]
I had the same Problem on Debian Bullseye and modifying the version check as suggested by alexander-haller fixed it for me, too.

**Comment by NicolasCARPi** [comment]
New version of elabctl released with that change.

**Comment by raymundfueloep** [comment]
That was fast - thank you!

**Comment by NicolasCARPi** [comment]
Well, can't really go wrong with a 1 character change :p

**Comment by raymundfueloep** [comment]
Famous last words ;-)

**Comment by NicolasCARPi** [comment]
> Famous last words ;-)

Pretty sure I can find in the history of elabftw a single character change with dire consequences.... ^^

**Comment by alexander-haller** [comment]
New version fixed it on Debian 11 - thanks as always.
"jq" is now a new dependency for elabctl beta check. In case someone reads this and still gets a warning.
