### ISSUE TITLE
Intended behaviour of the update mechanism

### ISSUE THREAD

**Issue by anargam** [elabftw/elabctl#25]
I was looking at a backup solution for eLabFTW machines, and stumbled upon a somewhat surprising bit in the elabctl update and backup semantics. In order of discovery:
* The current version of the script copies an elabftw.yml file so that a container can be restored (to whatever has the right tags online). 
* When restoring a previously working system from a backup, it is nice if the data and the code are consistent. The SQL dump might not be consistent with just any version of the code. 
* This does appear to be the responsibility of the user. The default is to use `elabftw/elabimg:latest`, and if we use this, the saved data will need some massaging to get it to run, if there have been eg schema changes or additional settings should be set (either to get it to run, or to get it to run securely and reliably). There are instructions about to how to change this.
* I propose that this is streamlined. I started a minor update in https://github.com/elabftw/elabctl/pull/26
* My code does *not* change the backed-up elabftw.yml, since this is not necessarily consistent with the elabctl update semantics that some might expect. (And note the number of "expect"-like words. This is just about consistency of expectations, and ease-of-use.)
* The current behaviour och `elabctl update` is to update to the latest versions of the containers. This is what is stated, and of course true regardless of which containers are pointed out (so, technically correct - the best kind of correct). But based on the update instructions on the web page, the _intention seems_ to be to update elabftw, rather than just go from an old version of the container tagged 4.0.1 to the latest bugfixed version of the container tagged 4.0.1 (as these things in practice seem to take place mostly between version numbers).
* One idea would be to have the elabftw.yml file reflect the current numbered version (eg 4.2.4, rather than "latest") and have the update mechanism update this.
* This would require the elabctl script to somehow figure out the latest version (the hacky solution would be "change to latest, pull, rewrite" but it's not nice). 
* Additionally, if there are large changes over and above just running update, of the run update2to3 variety, it would be nice if it suggests or enforces such updates.

There are of course multiple things that I haven't thought of, and I don't know the paradigmatic way of implementing it. Thus the issue, rather than me trying to write a fully-fledged hack ex ante. :)

**Comment by anargam** [comment]
Some additional thoughts, just to summarise: one version would be to have
* Clear notes about this in the documentation.
* Pinning by default. The ?config url could give you a file with the current latest.
* Some simple api that tells us which version is the latest (maybe just a static text file with a known and stable URL). This is both useful for elabctl and custom scripts that work directly with the docker-compose file.
* `elabctl get-latest` or something, that figures out if there is a newer version, updates the pinned version, and pulls down images. (This might sound a lot like 'update', but I dislike changing the semantics of that existing operation, for instance if someone has a pinned version in their yaml file and really want to keep using that version.) Again, clarifications in the help and documentations might prove useful.
* Automatic schema-checks in the application with user-information ("hey, the installed code is version 4.2.4, but the detected schema version is 65. Ask your sysadmin to run update:db to get the consistent schema version 69"). [This might be there already]

**Comment by NicolasCARPi** [comment]
> Pinning by default. The ?config url could give you a file with the current latest.

That's a good idea.

> maybe just a static text file with a known and stable URL

https://get.elabftw.net/updates.json

This is the URL used in sysadmin panel to fetch the latest stable version. Otherwise the github api works too!

> elabctl get-latest

I don't know, to me it seems when you want to update, if you have a pinned version, you edit your config file to match the version you want and then do the update which is basically a pull/down/up. This might also force users to actually go on the release page, **read the changelog**, and be mindful about what they are doing. I should also modify the tagging action so it tags 4.3 for 4.3.X so one can pin to 4.3 and always get minor versions without having to change the config file.

> Automatic schema-checks in the application with user-information

Yes it is there of course, it blocks the app and looks like this:

![2022-03-18-125116_1643x604_scrot](https://user-images.githubusercontent.com/3043706/158998285-619b8f0d-3f89-4741-9ac9-61382c580fd6.png)

**Comment by NicolasCARPi** [comment]
I have made the change to get.elabftw.net so the image is pinned to the latest stable version when you query the config.
