### ISSUE TITLE
Honoring /etc/elabctl.conf?

### ISSUE THREAD

**Issue by mjeltsch** [elabftw/elabctl#28]
elabctl does not honor /etc/elabctl.conf, but it does honor the same file when it is present in the same directory as the executable. Not serious but has thrown us again off by assuming we can just have all the config files under /etc

**Comment by NicolasCARPi** [comment]
It does honor the general file but a local one will override values:

~~~bash
# Now we load the configuration file for custom directories set by user
if [ -f /etc/elabctl.conf ]; then
    source /etc/elabctl.conf
    ELABCTL_CONF_FILE="/etc/elabctl.conf"
fi


# elabctl.conf in ~/.config
if [ -f "${HOME}/.config/elabctl.conf" ]; then
    source "${HOME}/.config/elabctl.conf"
    ELABCTL_CONF_FILE="${HOME}/.config/elabctl.conf"
fi


# if elabctl is in current dir it has top priority
if [ -f elabctl.conf ]; then
    source elabctl.conf
    ELABCTL_CONF_FILE="elabctl.conf"
fi
~~~

This is standard behavior, for instance `/etc/bashrc` would load first and `~/.bashrc` afterwards. But maybe it should be better documented then, to avoid surprises.

**Comment by mjeltsch** [comment]
Hi Nicolas,
This is the way it should work. For some reason, it seems not to. I fear
that also my recent trouble might have something to do with it:
https://github.com/elabftw/elabftw/issues/3479

P.S.: You close issues too fast for me. I have perhaps 30 minutes of time
per week to spend on this issue; sometimes you have to wait for a week
before I get around to doing something about your feedback.

**Comment by NicolasCARPi** [comment]
>  For some reason, it seems not to

Well, I cannot reproduce this issue. I tried changing some configuration options in the different files and they are correctly read/overwritten in the order it should.
