### ISSUE TITLE
Program 'jq' seems to be a prerequisite - mention this in install instructions?

### ISSUE THREAD

**Issue by ChrisHal** [elabftw/elabctl#29]
Hi,

I ran into a small issue running `elabctl update` on Debian:  

I got "Notice: 'jq' command not found, skipping release is beta check."

I did not have `jq` installed. Perhaps `jq` might be mentioned as a prerequisite in the installation instructions?

Best,
Christian

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for your comment, the documentation has been updated.
