### ISSUE TITLE
Make elabctl update ask for (re)installing same version

### ISSUE THREAD

**Issue by alexander-haller** [elabftw/elabctl#30]
Currently if you run  elabctl update it pulls the docker images and restarts everything even when you already have the current version.

Would it be a better idea to look if latest version = installed version and offer to do nothing?
Are there possible downsides?
I tested something like this:

```
function update
{
    is-installed
    has-disk-space
    installed_release=$(docker exec -it ${ELAB_WEB_CONTAINER_NAME} grep INSTALLED_VERSION /elabftw/src/classes/App.php | cut -d\' -f 2)
    echo "Found installed release: $installed_release"
    latest_release=$(curl -s https://api.github.com/repos/elabftw/elabimg/releases/latest | jq -r ".tag_name")
    echo "Found latest release: $latest_release"
    if [ "$latest_release" = "$installed_release" ]; then
        echo "Notice: the latest intalled version appears to be the current version, do you want perform a reinstall? (y/N)"
        read -r reinstall_current
        if [ ! "$reinstall_current" = "y" ]; then
            echo "Not reinstalling current version!"
            exit 0
        fi
    fi
    echo "Do you want to make a backup before updating? (y/N)"
    ....
}
```

```
root@elabftw-dev:~# elabctl update
Using elabctl configuration file: /etc/elabctl.conf
Using elabftw configuration file: /etc/elabftw.yml
---------------------------------------------
Found installed release: 4.3.10
Found latest release: 4.3.10
Notice: the latest intalled version appears to be the current version, do you want perform a reinstall? (y/N)
n
Not reinstalling current version!

```

**Comment by NicolasCARPi** [comment]
I don't see the incentive to add code for that. It's not like `elabctl update` should be run in a cronjob anyway.

**Comment by alexander-haller** [comment]
Incentive for me was mainly that I prefer update commands to behave like that (to do nothing if already up-to-date).
Restarting services without need should be avoided and some users might periodically call elabctl update manually (although ideally they would all follow and read the release notes) .
But I'm also on board with keeping the current behavior - for me personally I know when a new version is released.

**Comment by NicolasCARPi** [comment]
Maybe a "check-update" command would make sense then? And it could run before the update and cancel it if there is nothing to update. Now this sounds valuable. But it is basically what you can see on the sysadmin panel though.

**Comment by alexander-haller** [comment]
> Maybe a "check-update" command would make sense then? And it could run before the update and cancel it if there is nothing to update.

yes exactly something like that

> Now this sounds valuable. But it is basically what you can see on the sysadmin panel though.

yes, I just like it when I can do "more stuff" without leaving the shell ;-)
If there would be a "check-update" command we could even think to run this every time the users starts elabctl and print a notice on new versions (basically the shell equivalent to how it is on the web). But this should be coded optional to prevent problems with timeouts when there is no internet connection.

**Comment by NicolasCARPi** [comment]
Yes, many CLI tools actually check the version (like npm or composer) to display a message when it's not the latest.

**Comment by NicolasCARPi** [comment]
I believe the intended behavior can be achieved by using `docker compose up -d` instead of down and up. So now it does this in the update command. If the container is the same as the image, it's fast.
