### ISSUE TITLE
borg-backup fails if BORG_REMOTE_PATH is not set

### ISSUE THREAD

**Issue by Xenolevis** [elabftw/elabctl#36]
elabctl 3.6.1
bash 4.2.46

If BORG_REMOTE_PATH is undefined in elabctl.conf, elabctl borg-backup fails with this error:
`/usr/local/bin/elabctl: line 58: BORG_REMOTE_PATH: unbound variable`

It is because of `set -eu` on line 54.

Suggested fix: replace block at line 58
```
if [ -n "$BORG_REMOTE_PATH" ]; then
   export BORG_REMOTE_PATH="${BORG_REMOTE_PATH}"
fi
```
with
```
if [[ -v BORG_REMOTE_PATH ]]; then
   export BORG_REMOTE_PATH="${BORG_REMOTE_PATH}"
fi
```

It might be obvious but I'd like to stress nevertheless: it's `-v BORG_REMOTE_PATH` and not `-v "$BORG_REMOTE_PATH"`

**Comment by NicolasCARPi** [comment]
Hello,

Thank you very much for your contribution! :)
