### ISSUE TITLE
Missing cleanup of TMP_DIR

### ISSUE THREAD

**Issue by alexander-haller** [elabftw/elabctl#37]
Minor issue

elabctl creates a TMP_DIR here:
https://github.com/elabftw/elabctl/blob/779b0911dec26c3f1643bcdb967ffb152baa2ebd/elabctl.sh#L16

Since this is never removed a lot of dirs will be generated if you
1) leave the server running for a long time
2) say ;-) run elabctl in a daily cronjob for backups

> debian@elabftw:~$ l /tmp/ | wc
>      93     738    5645
> 

TMP_DIR itself is only used once in `function self-update` but the dependent variable `TMP_CONF_FILE` is often needed in `function install`

**Comment by NicolasCARPi** [comment]
I realize now I've adressed the issue wrongly in 5.0.2, so 5.0.3 should really fix this issue. Thanks for reporting it!
