### ISSUE TITLE
install page broken using this script

### ISSUE THREAD

**Issue by rawray7** [elabftw/elabctl#4]
i just tried following these instructions: http://elabftw.readthedocs.io/en/master/install-drop.html

i end up with a blank install page :
<img width="1391" alt="screen shot 2016-06-04 at 10 52 34 am" src="https://cloud.githubusercontent.com/assets/6441089/15801242/eb48fb8e-2a43-11e6-806b-8509a1a773ba.png">

i've tried 3 times now on two different servers - so i'm pretty sure there is a bug in the script.

the only noticeable discrepancy between the instructions and my actions is that the 1-click app Docker image on DO is now 1.11.2

**Comment by NicolasCARPi** [comment]
Hello,

It is indeed an error in the code. A function I forgot to rename... Weird that I didn't catch it earlier as I did multiple installs like that before... Anyway here is the fix:
https://github.com/elabftw/elabftw/commit/d77cc3dd1f4b2732407a3ff36cc0a6d591316c91

A new patch will come out soon.

Thanks for the report :)

Regards,
~Nico
