### ISSUE TITLE
Issue with older versions of Docker and elabctl backup

### ISSUE THREAD

**Issue by jdorigatti** [elabftw/elabctl#6]
It looks like some older versions of docker have an issue when `elabctl backup` is run under cron. 

Description: If `elabctl backup` is executed from a tty the script executes normally, but fails when executed by cron.

In particular this line (in elabctl) causes an error due to the tty call.
`docker exec -it mysql bash -c 'mysqldump -u$MYSQL_USER -p$MYSQL_PASSWORD -r dump.sql $MYSQL_DATABASE' > /dev/null 2>&1`

It can be fixed by changing the line to the one below.
`docker exec -i mysql bash -c 'mysqldump -u$MYSQL_USER -p$MYSQL_PASSWORD -r dump.sql $MYSQL_DATABASE' > /dev/null 2>&1`

This issue _MAY_ be fixed in the latest versions of docker but I have been unable to verify this. However this might be helpful to someone out there.

Docker version 1.13.0, build 49bf474
Ubuntu 16.04.1 LTS (Running on AWS)
elabctl version 0.2.1

**Comment by NicolasCARPi** [comment]
Hello,

Yes indeed, good catch, here is the bug in docker: https://github.com/docker/docker/issues/8755

I removed both the `-t` and the `-i` because they serve no purpose here.

Thanks for reporting the issue :)

~Nico
