### ISSUE TITLE
Error updating (image not found)

### ISSUE THREAD

**Issue by mcc-puretech** [elabftw/elabctl#9]
When updating elabftw using elabctl from a digitalocean droplet server:

> Status: Image is up to date for mysql:5.7
> Pulling web (elabftw/docker-elabftw:latest)...
> Pulling repository docker.io/elabftw/docker-elabftw
> ERROR: Error: image elabftw/docker-elabftw:latest not found

The rest of the update proceeds and _elabctl start_ reports that elabftw is up-to-date, but the sysadmin panel reports out-of-date.

**Comment by NicolasCARPi** [comment]
Hello,

Since version 1.4.0 the repository is named `elabftw/elabimg`. Please update your `/etc/elabftw.yml` file. I must admit that I didn't communicate enough on this change, and only recently deleted the old repo (which was forwarding requests to the new one).

**Comment by NicolasCARPi** [comment]
@mcc-puretech did you manage to update?

**Comment by mcc-puretech** [comment]
Yes, got it to work, thanks.

Michael

On Mar 10, 2017 08:14, Nicolas CARPi <notifications@github.com> wrote:

@mcc-puretech<https://github.com/mcc-puretech> did you manage to update?
